### PR TITLE
Change production retrieval

### LINKED ISSUE #14: Envoy Software version D5.0.34 data error
Hi,

I have an envoy that was working fine with HA until june. Now I have errors like this 
`"Got a response from 'http://envoy/production.json', but metric could not be found. Maybe your model of Envoy doesn't support the requested metric."`

The command : 
`curl 'http://envoy/production.json'`
Gives :
`{"production":[{"type":"inverters","activeCount":1,"readingTime":1572524639,"wNow":117,"whLifetime":482485}],"storage":[{"type":"acb","activeCount":0,"readingTime":0,"wNow":0,"whNow":0,"state":"idle"}]}`

And as the error states, there is not the requested metric for example in the code:  

`raw_json["production"][1]["wNow"]` 

There is only 1 element in the production array, and it doesn't contain the wNow attribute.

So it seems that either there is an upgrade of the Json format since a recent enphase upgrade either there is something wrong with my setup.

Is this library valid for this software version ? My model seems to be an S version, it is identified in the code by "PC", maybe the "/api/v1/production" endpoint is the right place to look for the production data now ?

### PR DESCRIPTION
**Pull request by gtdiehl**
Since there are two different Envoy-S models, one that has only inverters and one with inverters and CTs (eim).  The production method should retrieve watts from the inverters as all Envoy-S will have inverters.

### CODE REVIEW

**Comment by jesserizzo** [comment]
@gtdiehl Do I need to put a new build with your two PRs up in PyPi?

**Comment by jesserizzo** [comment]
Also, just remembering why I went with the eim numbers in the first place. They update second by second, the inverter numbers update much less often (15 minutes I think). Would it be too much trouble to try `production = raw_json["production"][1]["wNow"]` and if that doesn't exist fall back to production = `raw_json["production"][0]["wNow"]`

**Comment by gtdiehl** [comment]
@jesserizzo I can work on this one a bit more.  Maybe try and fall back if the oeim wNow not available to the inverter wNow.  Can you build a new library for PyPi without this change for now, just the other change for the exception message?

**Comment by jesserizzo** [comment]
@gtdiehl Ok, that's up at PyPi, version 0.11.0

**Comment by gtdiehl** [comment]
This seemed to me the quickest and cleanest way to get wNow information from the inverter section if the eim section is not available.  Closes #14

**Pull request merged**
